<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Ray-Ban Aviator Classic',
                'slug' => 'ray-ban-aviator-classic',
                'description' => 'Az Aviator Classic az egyik legikonikusabb napszemüveg a világon. Arany fémkeretének és teardrop alakú lencséjének köszönhetően örök klasszikus, amely minden alkalomra passzol.',
                'short_description' => 'Ikonikus pilóta fazon, UV400 védelem, arany keret.',
                'sku' => 'RB-AV-001',
                'price' => 850,
                'stock_quantity' => 15,
                'brand' => 'Ray-Ban',
                'model' => 'RB3025',
                'frame_material' => 'Fém',
                'lens_type' => 'G-15 zöld',
                'frame_color' => 'Arany',
                'frame_size' => '58-14-135',
                'gender' => 'unisex',
                'age_group' => 'adult',
                'is_sunglasses' => true,
                'is_prescription' => false,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Ray-Ban Wayfarer Fekete',
                'slug' => 'ray-ban-wayfarer-fekete',
                'description' => 'A Wayfarer az 1950-es évek óta a klasszikus cool szimbóluma. Vastag acetat kerete és szögletes vonalai máig trendinnek számítanak.',
                'short_description' => 'Örök klasszikus szögletes fazon, vastag acetat keret.',
                'sku' => 'RB-WF-002',
                'price' => 790,
                'sale_price' => 690,
                'stock_quantity' => 20,
                'brand' => 'Ray-Ban',
                'model' => 'RB2140',
                'frame_material' => 'Acetat',
                'lens_type' => 'Sötétített szürke',
                'frame_color' => 'Fekete',
                'frame_size' => '54-18-145',
                'gender' => 'unisex',
                'age_group' => 'adult',
                'is_sunglasses' => true,
                'is_prescription' => false,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Oakley Holbrook Polarizált',
                'slug' => 'oakley-holbrook-polarizalt',
                'description' => 'A Holbrook az aktív életmód kedvelőinek tervezett, retro ihletésű napszemüveg. Polarizált lencséje szinte teljesen megszünteti a vakító visszatükröződést.',
                'short_description' => 'Sport és stílus egyben, polarizált lencse.',
                'sku' => 'OAK-HB-003',
                'price' => 680,
                'stock_quantity' => 12,
                'brand' => 'Oakley',
                'model' => 'Holbrook',
                'frame_material' => 'O-Matter műanyag',
                'lens_type' => 'Polarizált Prizm',
                'frame_color' => 'Matt fekete',
                'frame_size' => '55-18-137',
                'gender' => 'male',
                'age_group' => 'adult',
                'is_sunglasses' => true,
                'is_prescription' => false,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Tommy Hilfiger Elegáns Keret',
                'slug' => 'tommy-hilfiger-elegans-keret',
                'description' => 'Letisztult, elegáns dioptriás szemüvegkeret acetatból. Irodai és formális alkalmakra egyaránt tökéletes.',
                'short_description' => 'Elegáns acetat keret, klasszikus fazon.',
                'sku' => 'TH-EL-004',
                'price' => 520,
                'stock_quantity' => 25,
                'brand' => 'Tommy Hilfiger',
                'model' => 'TH 1520',
                'frame_material' => 'Acetat',
                'lens_type' => 'Dioptriás (recept szerint)',
                'frame_color' => 'Havana barna',
                'frame_size' => '52-17-140',
                'gender' => 'female',
                'age_group' => 'adult',
                'is_sunglasses' => false,
                'is_prescription' => true,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Silhouette Titan Minimal',
                'slug' => 'silhouette-titan-minimal',
                'description' => 'Az osztrák Silhouette a világ legkönnyebb szemüvegeinek egyikét alkotja. Keret nélküli, titán csavarok tartják a lencséket — szinte érezhetetlen a viselése.',
                'short_description' => 'Keretmentes titán, ultra könnyű viselet.',
                'sku' => 'SIL-TI-005',
                'price' => 1200,
                'stock_quantity' => 8,
                'brand' => 'Silhouette',
                'model' => 'Titan Minimal Art',
                'frame_material' => 'Titán',
                'lens_type' => 'Dioptriás (recept szerint)',
                'frame_color' => 'Ezüst',
                'frame_size' => '54-19-145',
                'gender' => 'unisex',
                'age_group' => 'adult',
                'is_sunglasses' => false,
                'is_prescription' => true,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Prada Oversized Cat-Eye',
                'slug' => 'prada-oversized-cat-eye',
                'description' => 'Divatház minőség, markáns macskaszem formával. Fekete acetat kerete és arany logója elegáns, határozott megjelenést ad.',
                'short_description' => 'Olasz luxus, macskaszem fazon, UV400.',
                'sku' => 'PRA-CE-006',
                'price' => 1450,
                'sale_price' => 1190,
                'stock_quantity' => 6,
                'brand' => 'Prada',
                'model' => 'SPR 08Y',
                'frame_material' => 'Acetat',
                'lens_type' => 'Sötétített szürke',
                'frame_color' => 'Fekete/Arany',
                'frame_size' => '57-17-140',
                'gender' => 'female',
                'age_group' => 'adult',
                'is_sunglasses' => true,
                'is_prescription' => false,
                'is_active' => true,
                'featured' => true,
            ],
            [
                'name' => 'Nike Flexon Sport',
                'slug' => 'nike-flexon-sport',
                'description' => 'Sportcélokra tervezett rugalmas fémkeret, amely extrém hajlítás után is visszanyeri eredeti alakját.',
                'short_description' => 'Rugalmas fémkeret, sport életmódhoz.',
                'sku' => 'NK-FL-007',
                'price' => 390,
                'stock_quantity' => 18,
                'brand' => 'Nike',
                'model' => 'Flexon 883',
                'frame_material' => 'Flexon ötvözet',
                'lens_type' => 'Dioptriás (recept szerint)',
                'frame_color' => 'Gunmetal szürke',
                'frame_size' => '53-16-140',
                'gender' => 'male',
                'age_group' => 'adult',
                'is_sunglasses' => false,
                'is_prescription' => true,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Lacoste Junior Keret',
                'slug' => 'lacoste-junior-keret',
                'description' => 'Gyerekeknek tervezett tartós acetat keret, rugalmas szárvéggel és puha orrpárnával.',
                'short_description' => 'Gyerek szemüveg, rugalmas és tartós.',
                'sku' => 'LAC-JR-008',
                'price' => 280,
                'stock_quantity' => 22,
                'brand' => 'Lacoste',
                'model' => 'L3654',
                'frame_material' => 'Acetat',
                'lens_type' => 'Dioptriás (recept szerint)',
                'frame_color' => 'Kék',
                'frame_size' => '47-15-125',
                'gender' => 'kids',
                'age_group' => 'child',
                'is_sunglasses' => false,
                'is_prescription' => true,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Persol Polarizált Havana',
                'slug' => 'persol-polarizalt-havana',
                'description' => 'Az olasz Persol kézzel gyártott acetátkeretei a legfinomabb szemüvegek közé tartoznak. A meleg havana szín és a polarizált zöld lencse klasszikus mediterrán stílust sugároz.',
                'short_description' => 'Kézzel gyártott olasz acetat, polarizált.',
                'sku' => 'PER-PL-009',
                'price' => 960,
                'stock_quantity' => 10,
                'brand' => 'Persol',
                'model' => 'PO3092SM',
                'frame_material' => 'Acetat',
                'lens_type' => 'Polarizált zöld',
                'frame_color' => 'Havana',
                'frame_size' => '55-19-145',
                'gender' => 'male',
                'age_group' => 'adult',
                'is_sunglasses' => true,
                'is_prescription' => false,
                'is_active' => true,
                'featured' => false,
            ],
            [
                'name' => 'Gucci Slim Metal',
                'slug' => 'gucci-slim-metal',
                'description' => 'Vékony fémkeretű dioptriás szemüveg az olasz divatházból. Minimalista design, dupla orrnyereg.',
                'short_description' => 'Vékony fém keret, minimalista luxus.',
                'sku' => 'GUC-SL-010',
                'price' => 1350,
                'stock_quantity' => 7,
                'brand' => 'Gucci',
                'model' => 'GG0392O',
                'frame_material' => 'Fém',
                'lens_type' => 'Dioptriás (recept szerint)',
                'frame_color' => 'Arany',
                'frame_size' => '51-20-145',
                'gender' => 'female',
                'age_group' => 'adult',
                'is_sunglasses' => false,
                'is_prescription' => true,
                'is_active' => true,
                'featured' => false,
            ],
        ];

        foreach ($products as $data) {
            // updateOrCreate hogy ne duplázódjon ha újra futtatják
            Product::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
